us-76 Unittest für Role schreiben
solid-stack-solutions/voycar-backend pull request #42
Opened 2024-06-13 09:19 UTC by kvnlnk

[User story 76](https://tree.taiga.io/project/julius-boettger-voycar/us/76)

2024-06-13 13:40 UTC, julius-boettger requested changes

2024-06-13 13:40 UTC, julius-boettger commented on Voycar.Api.Web.Tests.Unit/Roles/Endpoints/Get/All.cs
> +    private readonly JsonSerializerOptions options = new()
```suggestion
    private readonly JsonSerializerOptions options = new ()
```

2024-06-13 13:40 UTC, julius-boettger commented on Voycar.Api.Web.Tests.Unit/Roles/Endpoints/Get/Single.cs
> +    private readonly JsonSerializerOptions options = new()
```suggestion
    private readonly JsonSerializerOptions options = new ()
```

2024-06-13 13:40 UTC, julius-boettger commented on Voycar.Api.Web.Tests.Unit/Roles/Endpoints/Post/SingleUnique.cs
> +    private readonly JsonSerializerOptions options = new()
```suggestion
    private readonly JsonSerializerOptions options = new ()
```

2024-06-13 13:50 UTC, julius-boettger reviewed
Vielleicht findet irgendwer noch was Schöneres raus als die Response mit dem `MemoryStream`

2024-06-13 13:50 UTC, julius-boettger commented on Voycar.Api.Web.Tests.Unit/Roles/Endpoints/Get/All.cs
> +        var rsp = ep.HttpContext.Response;
Vielleicht finden wir hier noch was Schöneres, um die Response zu bekommen als `MemoryStream`. Wenn nicht, würde ich die PR approven/mergen.

2024-06-13 14:42 UTC, kvnlnk commented on Voycar.Api.Web.Tests.Unit/Roles/Endpoints/Get/All.cs
> +        var rsp = ep.HttpContext.Response;
Ich gucke heute Abend nochmal

2024-06-14 10:45 UTC, julius-boettger approved these changes

2024-06-14 10:45 UTC, merged