us-139 Unittest für Register-Endpoint schreiben
solid-stack-solutions/voycar-backend pull request #45
Opened 2024-06-17 16:08 UTC by kvnlnk

[User story 139](https://tree.taiga.io/project/julius-boettger-voycar/us/139)

In diesen Unittests wird für den Register-Endpoint überprüft, ob er die entsprechenden Statuscodes (200,400) liefert. Die Request-Validation sollte in einem Integrationtest überprüft werden.

2024-06-17 20:25 UTC, julius-boettger reviewed
Befolgen die Methodenbezeichner Nils' Convention? Hab gerade nicht im Kopf wie das nochmal aussehen sollte. Sonst noch andere kleine Fragen.

2024-06-17 20:25 UTC, julius-boettger commented on Voycar.Api.Web.Tests.Unit/Users/Post/Register/Endpoint.cs
> +        A.CallTo(() => fakeUserRepository.RetrieveByEmail(req.Email.ToLowerInvariant())).Returns((User?)null);
Wofür das `ToLowerInvariant()`? `req.Email` besteht doch sowieso nur aus Kleinbuchstaben.

Und was macht das `null` da am Ende?

2024-06-17 20:25 UTC, julius-boettger commented on Voycar.Api.Web.Tests.Unit/Users/Post/Register/Endpoint.cs
> +        A.CallTo(() => fakeUserRepository.RetrieveByEmail(req.Email.ToLowerInvariant())).Returns(user);
Selbe Frage wie vorher. `ToLowerInvariant()` nötig?

2024-06-17 20:28 UTC, kvnlnk commented on Voycar.Api.Web.Tests.Unit/Users/Post/Register/Endpoint.cs
> +        A.CallTo(() => fakeUserRepository.RetrieveByEmail(req.Email.ToLowerInvariant())).Returns((User?)null);
Hatte die Methode nur kopiert. Das null ist dafür da, weil ich keinen User zurückbekommen will. Das mit der Bezeichnung hatte ich gar nicht auf den Schirm, kann ich noch anpassen

2024-06-17 20:29 UTC, kvnlnk commented on Voycar.Api.Web.Tests.Unit/Users/Post/Register/Endpoint.cs
> +        A.CallTo(() => fakeUserRepository.RetrieveByEmail(req.Email.ToLowerInvariant())).Returns(user);
Auch hier, ist kopiert aus dem richtigen Endpoint. Kann ich noch anpassen, macht aber keinen Unterschied

2024-06-17 20:34 UTC, julius-boettger commented
Noch eine Frage: Das `var req = new Request { ... }` sieht mir aus, als wär es in beiden Test Cases exakt dasselbe. Finde ich eigentlich unnötig redundant diesen ganzen Code da zweimal zu haben. Kann man das irgendwie auslagern, dass man das nur einmal schreiben muss? Keine Ahnung, was da der Best Practice für ist, ich hätte jetzt vielleicht an ein privates, konstantes Klassenattribut gedacht oder so...

2024-06-17 20:36 UTC, kvnlnk commented
Hab ich auch schon überlegt, werde ich mich morgen nochmal ransetzen. Bei dem anderen Branch wird es ähnlich sein

2024-06-18 14:24 UTC, julius-boettger approved these changes

2024-06-18 14:25 UTC, julius-boettger requested changes

2024-06-18 14:25 UTC, julius-boettger commented on Voycar.Api.Web.Tests.Unit/Users/Post/Register/Endpoint.cs
> +    private readonly Request request = new()
Das sollte `Request` und nicht `request` heißen, bitte überall ändern

2024-06-18 14:26 UTC, julius-boettger requested changes
Alle Attribute sollten PascalCase sein. Z. B. `Request` und `FakeLogger` anstatt `request` und `fakeLogger`. Bitte ändern.

2024-06-18 14:35 UTC, julius-boettger approved these changes

2024-06-18 14:35 UTC, merged