us-41 .editorconfig anpassen
solid-stack-solutions/voycar-backend pull request #55
Opened 2024-06-20 20:32 UTC by Kenoalpe

[User story 41](https://tree.taiga.io/project/julius-boettger-voycar/us/41)

2024-06-20 20:52 UTC, julius-boettger requested changes
Zwei Dinge:
- Warum hast du jetzt überall `_repository` zu `repository` geändert?
- Bekommen wir irgendwie auch noch die Warning [CA1716](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1716) weg, wenn Keywords wie `get` im Namespace sind?

2024-06-20 20:59 UTC, Kenoalpe commented
> Zwei Dinge:
> 
>     * Warum hast du jetzt überall `_repository` zu `repository` geändert?
> 
>     * Bekommen wir irgendwie auch noch die Warning [CA1716](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1716) weg, wenn Keywords wie `get` im Namespace sind?

- Weil der _ nur für privat field sein sollte, auch wenn ich gerade nicht weiß wie konsistent das sonst
- Hab ich auf silent gestellt

2024-06-21 05:57 UTC, julius-boettger commented
> Weil der _ nur für privat field sein sollte, auch wenn ich gerade nicht weiß wie konsistent das sonst

Hmmm... ich hab neulich die US bearbeitet, in der ich überprüft habe, dass alle Attribute von Klassen konsistent benannt sind. Und da bin ich nach folgenden Regeln vorgegangen, die ich bisher auch so von dir verstanden habe:
- Erstmal alles PascalCase
- Dependency Injected Attribute: camelCase mit Unterstrich davor, z. B. `_repository`

Der Unterstrich hatte also bisher nichts mit Private/Public zu tun, sondern mit Dependency Injection. Würd ich eigentlich auch gern so behalten.

2024-06-21 06:01 UTC, julius-boettger commented
Und noch was Kleines (wenn dus schnell fixen kannst): In den Tests bekommen wir ganz viel die Warning [CA1707](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1707), weil unsere Test-Methoden Bezeichner mit Unterstrichen haben, z. B. `Get_Available_ReturnsBadRequest_DueToNegativeTime`. Wär cool wenn du das auch noch ignorieren/ausstellen könntest.

2024-06-21 08:35 UTC, Kenoalpe commented
Oke, sollte ich beides angepassts haben

2024-06-21 08:50 UTC, Kenoalpe commented
Oke, sry einmal für die ganzen commits sollte jetzt gelöst sein.

Merke: Drop Commit macht komische Sachen, wenn man es nicht genau versteht.

2024-06-21 08:59 UTC, Janniix approved these changes
Lgtm. 👋

2024-06-21 09:12 UTC, julius-boettger approved these changes

2024-06-21 09:12 UTC, merged